workspace:
  base: /go
  path: src/github.com/Nordstrom/choices

pipeline:
  build:
    image: golang:1.7.1
    commands:
      - go install cmd/...
  test:
    image: golang:1.7.1
    commands:
      - cd $GOPATH/src/github.com/Nordstrom/choices
      - go test . -bench=. -benchmem
