apiVersion: v1
kind: ConfigMap
data:
  config.toml: |
    listen_address = ":8080"

    [clients]
    {{ .Values.houston.prodIntake }} = "{{ .Values.houston.prodStorage }}"
    {{ .Values.houston.devIntake }} = "{{ .Values.houston.devStorage }}"
